force-app/main/default/objects/My_Accounts__c/My_Accounts__c.object-meta.xml
<CustomObject>
    <label>My Accounts</label>
    <nameField>
        <label>Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/My_Transactions__c/My_Transactions__c.object-meta.xml
<CustomObject>
    <label>My Transactions</label>
    <nameField>
        <displayFormat>Transaction no-{0}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>My Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/My_Transactions__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>17</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/My_Transactions__c/fields/My_Accountss__c.field-meta.xml
<CustomField>
    <fullName>My_Accountss__c</fullName>
    <label>My Accountss</label>
    <referenceTo>My_Accounts__c</referenceTo>
    <relationshipLabel>My Transactions</relationshipLabel>
    <relationshipName>My_Transactions1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/My_Transactions__c/fields/Transaction_date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_date__c</fullName>
    <formula>TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Transaction date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/My_Transactions__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/My_Transactions__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Credited</fullName>
            </value>
            <value>
                <fullName>Debited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MyTransactionsController.cls
/**
 * Apex controller for retrieving My Transactions records.
 */
public with sharing class MyTransactionsController {
    /**
     * Retrieves a list of My Transactions records.
     *
     * @return List of My_Transactions__c records.
     */
    
    @AuraEnabled(cacheable=true)
    public static List<My_Transactions__c> getTransactions() {
        return [SELECT Id, Amount__c, Transaction_date__c, My_Accountss__r.Name, Transaction_Status__c,
                Transaction_Type__c FROM My_Transactions__c limit 10];
    }
}