force-app/main/default/objects/My_Accounts__c/My_Accounts__c.object-meta.xml
<CustomObject>
    <label>My Accounts</label>
    <nameField>
        <label>Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/My_Accounts__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saving</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/My_Accounts__c/fields/My_Customers__c.field-meta.xml
<CustomField>
    <fullName>My_Customers__c</fullName>
    <label>My Customers</label>
    <referenceTo>My_Customers__c</referenceTo>
    <relationshipLabel>My Accounts</relationshipLabel>
    <relationshipName>My_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/My_Accounts__c/fields/Total_Deposits__c.field-meta.xml
<CustomField>
    <fullName>Total_Deposits__c</fullName>
    <defaultValue>00</defaultValue>
    <label>Total Deposits</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/My_Accounts__c/fields/Total_Withdrawals__c.field-meta.xml
<CustomField>
    <fullName>Total_Withdrawals__c</fullName>
    <defaultValue>00</defaultValue>
    <label>Total Withdrawals</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/My_Customers__c/My_Customers__c.object-meta.xml
<CustomObject>
    <label>My Customers</label>
    <nameField>
        <label>Customers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/My_Customers__c/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhar Number</label>
    <length>12</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/My_Customers__c/fields/Account_Creation_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Creation_Status__c</fullName>
    <defaultValue>&quot;Under Review&quot;</defaultValue>
    <label>Account Creation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under Review</fullName>
                <color>#6666CC</color>
                <label>Under Review</label>
            </value>
            <value>
                <fullName>Account Created Successfully</fullName>
                <color>#009900</color>
                <label>Account Created Successfully</label>
            </value>
            <value>
                <fullName>Account Creation Rejected</fullName>
                <color>#FF0000</color>
                <label>Account Creation Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/My_Customers__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saving</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/My_Customers__c/fields/First_Deposit_Amount__c.field-meta.xml
<CustomField>
    <fullName>First_Deposit_Amount__c</fullName>
    <label>First Deposit Amount</label>
    <precision>17</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/My_Transactions__c/My_Transactions__c.object-meta.xml
<CustomObject>
    <label>My Transactions</label>
    <nameField>
        <displayFormat>Transaction no-{0}</displayFormat>
        <label>Transaction</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>My Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/My_Transactions__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>17</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/My_Transactions__c/fields/My_Accountss__c.field-meta.xml
<CustomField>
    <fullName>My_Accountss__c</fullName>
    <label>My Accountss</label>
    <referenceTo>My_Accounts__c</referenceTo>
    <relationshipLabel>My Transactions</relationshipLabel>
    <relationshipName>My_Transactions1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/My_Transactions__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/My_Transactions__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Credited</fullName>
            </value>
            <value>
                <fullName>Debited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_MyTransactionsTriggersAndHandler.cls
@isTest
public class Test_MyTransactionsTriggersAndHandler {
    // Test method to cover trigger logic
    static testMethod void testTriggerLogic() {
        
         // Create test data for My_Customers__c records
       My_Customers__c customertest = new My_Customers__c(
            Name = 'Customer 1',
            Account_Creation_Status__c = 'Under Review', // Initial status
            Account_Type__c = 'Saving',
            Aadhar_Number__c ='4364623652',
            First_Deposit_Amount__c = 10000
        );
        insert customertest;

        // Update the Account_Creation_Status__c to 'Account Created Successfully'
        
        customertest.Account_Creation_Status__c = 'Account Created Successfully';
        update customertest;
  
        // Create test data for My_Accounts__c records
        My_Accounts__c testAccount = new My_Accounts__c(
            Name = 'Test Account',
            My_Customers__c = customertest.Id
        );
        insert testAccount;

        // Create test data for My_Transactions__c records
        My_Transactions__c depositTransaction = new My_Transactions__c(
            Amount__c = 200,
            Transaction_Type__c = 'deposit',
            Transaction_Status__c = 'Pending',
            My_Accountss__c = testAccount.Id
        );

        My_Transactions__c withdrawalTransaction = new My_Transactions__c(
            Amount__c = 100,
            Transaction_Type__c = 'withdrawal',
            Transaction_Status__c = 'Pending',
            My_Accountss__c = testAccount.Id
        );
        
                
          My_Transactions__c depositTransaction1 = new My_Transactions__c(
            Amount__c = 60000,
            Transaction_Type__c = 'deposit',
            Transaction_Status__c = 'Pending',
            My_Accountss__c = testAccount.id
        );


        insert new List<My_Transactions__c>{ depositTransaction, withdrawalTransaction,depositTransaction1 };

        // Trigger should update transaction status and total deposits/withdrawals
        List<My_Transactions__c> updatedTransactions = [SELECT Id, Transaction_Status__c FROM My_Transactions__c];
        System.assertEquals('Success', updatedTransactions[0].Transaction_Status__c);
        System.debug('check 1');
        System.assertEquals('Success', updatedTransactions[1].Transaction_Status__c);
        System.debug('check 2');
         System.assertEquals('Pending', updatedTransactions[2].Transaction_Status__c);

        List<My_Accounts__c> updatedAccounts = [SELECT Id, Total_Deposits__c, Total_Withdrawals__c FROM My_Accounts__c];
        System.assertEquals(10000, updatedAccounts[0].Total_Deposits__c);
          System.debug('check 1');
        System.assertEquals(100, updatedAccounts[1].Total_Withdrawals__c);
          System.debug('check 2');
    }
}