force-app/main/default/objects/My_Accounts__c/My_Accounts__c.object-meta.xml
<CustomObject>
    <label>My Accounts</label>
    <nameField>
        <label>Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/My_Accounts__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saving</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/My_Accounts__c/fields/My_Customers__c.field-meta.xml
<CustomField>
    <fullName>My_Customers__c</fullName>
    <label>My Customers</label>
    <referenceTo>My_Customers__c</referenceTo>
    <relationshipLabel>My Accounts</relationshipLabel>
    <relationshipName>My_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/My_Customers__c/My_Customers__c.object-meta.xml
<CustomObject>
    <label>My Customers</label>
    <nameField>
        <label>Customers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/My_Customers__c/fields/Aadhar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Number__c</fullName>
    <label>Aadhar Number</label>
    <length>12</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/My_Customers__c/fields/Account_Creation_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Creation_Status__c</fullName>
    <defaultValue>&quot;Under Review&quot;</defaultValue>
    <label>Account Creation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under Review</fullName>
                <color>#6666CC</color>
                <label>Under Review</label>
            </value>
            <value>
                <fullName>Account Created Successfully</fullName>
                <color>#009900</color>
                <label>Account Created Successfully</label>
            </value>
            <value>
                <fullName>Account Creation Rejected</fullName>
                <color>#FF0000</color>
                <label>Account Creation Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/My_Customers__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saving</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/My_Customers__c/fields/First_Deposit_Amount__c.field-meta.xml
<CustomField>
    <fullName>First_Deposit_Amount__c</fullName>
    <label>First Deposit Amount</label>
    <precision>17</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Test_MyCustomerNewAccountHandler.cls
/**
 * Test_MyCustomerNewAccountHandler - Test class for testing the trigger logic in MyCustomerNewAccountHandler.
 * This test class validates the trigger logic that creates My_Accounts__c records when My_Customers__c records are updated.
 */
@isTest
public class Test_MyCustomerNewAccountHandler {
    
    /**
     * Test method to cover the trigger logic.
     */
    static testMethod void testTriggerLogic() {
        
        // Create test data for My_Customers__c records
        
        My_Customers__c customer1 = new My_Customers__c(
            Name = 'Customer 1',
            Account_Creation_Status__c = 'Under Review', // Initial status
            Account_Type__c = 'Saving',
            Aadhar_Number__c ='4364623652',
            First_Deposit_Amount__c = 10000
        );
        insert customer1;

        // Update the Account_Creation_Status__c to 'Account Created Successfully'
        
        customer1.Account_Creation_Status__c = 'Account Created Successfully';
        update customer1;

        // Verify that a My_Accounts__c record is created for the customer
        
        List<My_Accounts__c> accounts = [SELECT Id FROM My_Accounts__c WHERE My_Customers__c = :customer1.Id];
        System.assertEquals(1, accounts.size(), 'Expected one My_Accounts__c record to be created');
    }
}